#!/usr/bin/env perl
use Mojolicious::Lite;
use DBIx::Connector;

my $conn
  = DBIx::Connector->new("dbi:Pg:$ENV{DATABASE_URL}", '', '',
  {AutoCommit => 0})
  or die;
$conn->mode('fixup');

helper get_header_value => sub { return shift->req->headers->header(shift) };

helper format_number => sub {
  use Number::Format;
  my ($self, $n) = @_;
  state $f = Number::Format->new(-thousands_sep => ',', -decimal_point => '.');
  return $f->format_number($n);
};

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

get '/test' => sub {
  my $self = shift;
  $self->stash(headers => $self->req->headers);
  $self->render;
};

get '/op';

under '/op/:op' => [op => qr/\d+/];

get '/' => sub {
  my $self = shift;
  my $op   = $self->param('op');
  $self->render('op-index');
};

get '/harvest_table';
get '/loot_table';

post '/add_harvest' => sub {
  my $self = shift;
  $self->redirect_to('/');
};

get '/join' => sub {
  my $self = shift;
  $self->redirect_to('/');
};

get '/finish' => sub {
  my $self = shift;
  $self->redirect_to('/');
};

app->start;
